### ISSUE TITLE
little problem with thaumcraft

### ISSUE THREAD

**Issue by SirioIlBe** [pupnewfster/GGSkyblock#27]
im trying to create mycelium so i can make mushrooms, and to do that you need to use the alchemy system from thaumcraft, but it doesn't seem to work. i put in obsidian and bread so i should have all the things i need to be able to craft mycelium, but when i throw the grass block in the crucible it just gets added as another ingredient and doesn't craft the mycelium. i don't know if its me that is doing something wrong or is a bug. its the first time im using this mod and i already hating it...

edit. now i have some kind of portal in the middle of my base that doesn't go away...great...really a great mod -.-"

**Comment by SirioIlBe** [comment]
ok thx...i didn't knew about this option

**Comment by SirioIlBe** [comment]
i can't transform passive animals with the philosopher's stone. what coal are you talking about?) i tried with normal coal and alchemical coal and nothing happens). plus now because thaumcraft all my animals (and me) have flux flu and flux phage . i don't know what that does. and i still have that strange portal in the middle of my base -.-" how can i remove it?

**Comment by pupnewfster** [comment]
Honestly not sure what portal you are talking about. Unless you mean a flux rift, which you either need to let eat up all the flux and expire turning into some sort of plant that you have to kill, or you have to drop/explode a `Cuasality Collapser` into it. I think if you have cheats enabled/open lan and select cheats enabled. You can type `/kill @e[type=thaumcraft:fluxrift]` or maybe it is `/kill @e[type=FluxRift]` not sure. Also sorry I thought I had mentioned that you had to use r to fire the projectile.

**Comment by SirioIlBe** [comment]
it disappeared by itself after some time.

**Comment by pupnewfster** [comment]
Next update (probably sometime this weekend) will have quests that describe things a bit better when it comes to mushrooms)
