### ISSUE TITLE
Vis Crystals

### ISSUE THREAD

**Issue by Veranath** [pupnewfster/GGSkyblock#48]
Unable to use Vis Crystals for infusions. Says I dont meet the requirements.

**Comment by pupnewfster** [comment]
That is so that you can't emc them and start getting random vis crystals for free basically. Use a hopper or some sort of pipe to put them into the infusion pedestals. For the next version I will make a note of it in a quest because other people may have the same issue/confusion.

**Comment by pupnewfster** [comment]
Keeping this open for now, mainly so I remember to add it to the quest.
