### ISSUE TITLE
Living armor uncraftable

### ISSUE THREAD

**Issue by Frinn38** [pupnewfster/GGSkyblock#53]
Because you can't right click with an iron armor (because "only for crafting") it is impossible to make the blood magic living armor with arcane ash and binding reagent.
Perhaps add a craft like the one for bound blade or completly disable the living armor.

**Comment by pupnewfster** [comment]
Thanks for pointing that out, I probably will add a recipe similar to how I have the bound blade. I will also look into seeing if there are any other recipe like it I missed when making the work around for the bound blade.

**Comment by pupnewfster** [comment]
Scratch that, given this issue made me think of another way of how it can be done, so I am implementing a way into compatskills that will let me allow using the armor/tools on the arcane ashe, but not use it otherwise. I will also then remove the makeshift recipes for bound items.

**Comment by Frinn38** [comment]
Thanks for your reply =D
Hope that you will find a way to implement arcane ash crafting in compatskills, I really love the living armor system ^^

**Comment by pupnewfster** [comment]
I have found a way to implement arcane ash crafting in compat skills. Just trying to clean up the implementation a bit more so it is easier to read the tooltip in general, and also maybe add some compat with getting astral sorcery states.

**Comment by pupnewfster** [comment]
Next version will include this, was closed by https://github.com/pupnewfster/GGSkyblock/commit/24925bec979ff076c0258924ab06b533333d6053 but I typed the wrong issue number so it didn't link itself.
