### ISSUE TITLE
Iridium nugget craftable with platinum dust

### ISSUE THREAD

**Issue by Frinn38** [pupnewfster/GGSkyblock#57]
No idea of if this is intended or not but you can get iridium without killing villagers, just make some nuggets in the industrial centrifuge using platinum dust.

**Comment by pupnewfster** [comment]
I hadn't realized about it, but it is fine. The main reason I included iridium ore is for a bit higher emc values. (And so that later on if people don't want to mess around with UU-Matter to make the ore, they don't have to)
